export const signupApi = new Promise((resolve) => resolve())
export const checkUserCredentialsApi = new Promise((resolve) => resolve())
export const addProductApi = new Promise((resolve) => resolve())
export const fetchProductsApi = new Promise((resolve) => resolve())
export const fetchForexRatesApi = new Promise((resolve) => resolve())
export const deleteProductApi = new Promise((resolve) => resolve())
export const updateProductApi = new Promise((resolve) => resolve())
